// eslint-disable-next-line no-restricted-syntax
export enum DemoPath {
    HomePage = 'home',
    CommonPage = 'common',
    PlatformPage = 'platform',
    UniversalPage = 'universal',
    AudioPage = 'audio',
    ResizeObserverPage = 'resize-observer',
    CanvasPage = 'canvas',
    SpeechPage = 'speech',
    GeolocationPage = 'geolocation',
    ScreenOrientation = 'screen-orientation',
    IntersectionObserverPage = 'intersection-observer',
    MutationObserverPage = 'mutation-observer',
    PaymentRequestPage = 'payment-request',
    MidiPage = 'midi',
    PermissionsPage = 'permissions',
    StoragePage = 'storage',
    WorkersPage = 'workers',
    ViewTransitionPage = 'view-transition',
    Notification = 'notification',
}
