export * from './directives/text-to-speech.directive';
export type * from './interfaces/speech-synthesis-utterance-options';
export * from './operators/confidence-above';
export * from './operators/continuous';
export * from './operators/final';
export * from './operators/first-alternative';
export * from './operators/skip-until-said';
export * from './operators/take-until-said';
export * from './pipes/utterance.pipe';
export * from './services/speech-recognition.service';
export * from './tokens/speech-recognition-max-alternatives';
export * from './tokens/speech-recognition-support';
export * from './tokens/speech-synthesis-support';
export * from './tokens/speech-synthesis-voices';
export * from './utils/is-said';
