name: ⚙️ CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
      - uses: taiga-family/actions/setup-node@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
      - run: npm run typecheck
      - run: npm run cspell
      - run: npx nx run-many -t build --exclude demo
      - run: npx nx run-many -t test
      - run: npx nx build-gh-pages demo

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run stylelint -- --fix
              npm run prettier -- --write
              npm run lint -- --fix
          else
              npm run stylelint
              npm run prettier -- --check
              npm run lint
          fi
      - uses: taiga-family/actions/auto-push@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
