name: ⚙️ CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@ef883fc6417f920333ffa8b903683d7d6b914615 # v1.201.0
      - uses: taiga-family/ci/actions/setup/node@ef883fc6417f920333ffa8b903683d7d6b914615 # v1.201.0
      - run: npm run typecheck
      - run: npm run cspell
      - run: npx nx run-many -t build --exclude demo
      - run: npx nx run-many -t test
      - run: npx nx build-gh-pages demo

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run stylelint -- --fix
              npm run prettier -- --write
              npm run lint -- --fix
          else
              npm run stylelint
              npm run prettier -- --check
              npm run lint
          fi
      - uses: taiga-family/ci/actions/auto/push@ef883fc6417f920333ffa8b903683d7d6b914615 # v1.201.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
