name: 🚀 Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-node@ed4e7ce7c012436a5f2b02d2b5a7aa86581db73a # v2.14.0
      - run: npx nx build-gh-pages demo
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          branch: gh-pages
          folder: dist/demo/browser
          silent: false
          clean: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
