name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-variables@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0
      - uses: taiga-family/actions/setup-node@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0
      - run: npx nx build-firebase-preview demo

      - uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0
        continue-on-error: true
        if: ${{ env.SUPPORT_AUTO_PUSH == 'true' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NG_WEB_APIS_COMMON }}
          projectId: ng-web-apis-common
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
